# Generated by Django 3.2 on 2022-04-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fulname',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='fulname',
            new_name='fullname',
        ),
    ]
